version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

networks:
  laravel_network:
    driver: bridge
