version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app-container
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

  # SQLite is embedded in the app, so no need for a separate container
  # We can use a volume to persist SQLite data

networks:
  laravel_network:
    driver: bridge
